spring.application.name=smart-career-assistant
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH0_AUDIENCE}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.groq.api-key=${GROQ_API_KEY}
app.groq.model=${GROQ_MODEL:llama-3.1-8b-instant}
app.groq.url=${GROQ_URL:https://api.groq.com/openai/v1/chat/completions}
